version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    doxygen: "1.9.8"
  jobs:
    pre_build:
      - doxygen docs/Doxyfile
      - python -m breathe.apidoc -f -g namespace,class,struct -o docs/api/generated docs/_build/doxygen/xml

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
